homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret geo_latitude
  longitude: !secret geo_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 115
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/New_York
  customize: 
  # Temperatures
    sensor.basement_temperature:
      icon: mdi:temperature-fahrenheit
    sensor.basement_temperature_2:
      friendly_name: "Basement Temp (ecobee)"
      icon: mdi:temperature-fahrenheit
    sensor.connor_temperature:
      friendly_name: "Connor's Room"
      icon: mdi:temperature-fahrenheit
    sensor.kaitlyn_temperature:
      friendly_name: "Kaitlyn's Room"
      icon: mdi:temperature-fahrenheit
    sensor.mbr_temperature:
      icon: mdi:temperature-fahrenheit
    sensor.master_bedroom_temperature:
      friendly_name: "MBR Temp (ecobee)"
      icon: mdi:temperature-fahrenheit
    sensor.garage_temperature:
      icon: mdi:temperature-fahrenheit
    sensor.home_temperature:
      icon: mdi:temperature-fahrenheit
    sensor.tv_room_temperature:
      icon: mdi:temperature-fahrenheit
  # Humidity
    sensor.basement_humidity:
      icon: mdi:water-percent
    sensor.mbr_humidity:
      icon: mdi:water-percent
    sensor.garage_humidity:
      icon: mdi:water-percent
    sensor.home_humidity:
      icon: mdi:water-percent
  # Doors
    sensor.garage_door:
      sensor_class: opening
  # Batteries
    sensor.keiths_phone:
      icon: mdi:battery
    sensor.keiths_E8_tablet:
      icon: mdi:battery
    sensor.jenns_E8_tablet:
      icon: mdi:battery
  # Occupancy
    binary_sensor.basement_occupancy:
      sensor_class: occupancy
    binary_sensor.connor_occupancy:
      sensor_class: occupancy
    binary_sensor.home_occupancy:
      sensor_class: occupancy
    binary_sensor.kailtyn_occupancy:
      sensor_class: occupancy
    binary_sensor.master_bedroom_occupancy:
      sensor_class: occupancy
    binary_sensor.tv_room_occupancy:
      sensor_class: occupancy
  # Switches
    switch.basement_stairs:
      friendly_name: "Basement Stairs Light"
      icon: mdi:lightbulb
    switch.tv_room:
      friendly_name: "TV Room Lamp"
      icon: mdi:lightbulb
    switch.fauxmo_switch:
      friendly_name: "Fauxmo Relay"
    sensor.pihole:
      friendly_name: "Pi-Holed Ads"
      icon: mdi:block-helper
  # Sensor Device Tracker
    device_tracker.esp8266_alarm:
      icon: mdi:radar
    device_tracker.esp8266_basement:
      icon: mdi:radar
    device_tracker.esp8266_garage:
      icon: mdi:radar
    device_tracker.esp8266_mbr_weather:
      icon: mdi:radar

# Show links to resources in log and frontend
#introduction:

# Enable the config tool
config:

# Enables the frontend
frontend:
  themes: !include_dir_merge_named themes/

http:
  # Uncomment this to add a password (recommended!)
  # api_password: PASSWORD

# Checks for available updates
updater:

# Discover some devices automatically
discovery:

# Display a Map of device locations
map:

wemo:
  static:
    - 10.0.0.44
    - 10.0.0.45
    - 10.0.0.46
    - 10.0.0.47
    - 10.0.0.48
    - 10.0.0.201

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:
  exclude:
    domains:
      - camera
    entities:
      - group.alerts
      - group.automations_view
      - group.basement
      - group.bedroom
      - group.cameras
      - group.darksky
      - group.default_view
      - group.devices
      - group.doors
      - group.ecobee
      - group.garage
      - group.humidities
      - group.iss
      - group.jenns_devices
      - group.keiths_devices
      - group.occupancy
      - group.occupancy_matrix
      - group.octoprint
      - group.outside
      - group.sun
      - group.temperatures
      - group.tvroom
      - group.weather

# View all events in a logbook
logbook:

# Track the sun
sun:

# ecobee thermostat
ecobee:
  api_key: !secret ecobee_key 

# TVs and media players
media_player:
  - platform: samsungtv
    host: 10.0.0.23
    name: "TV Room LED TV"
  - platform: samsungtv
    host: 10.0.0.24
    name: "Bedroom Plasma TV"
  - platform: samsungtv
    host: 10.0.0.25
    name: "Basement LED TV"
    port: 8001
    mac: !secret basement_tv_mac
#  - platform: ps4
#    host: 10.0.0.9
#    cmd: 'sudo ps4-waker'
  - platform: plex
    entity_namespace: 'plex'
    include_non_clients: true
    scan_interval: 5
    show_all_controls: false
    use_custom_entity_ids: true
    use_episode_art: true

# Control HDMI devices in TV-Room
#hdmi_cec:
#  devices:
#    1: Tivo
#    2: Soundbar
#    3: PS3
#    4: RasPi
    
input_select:
  tv_input:
    name: TV
    options:
     - 'OFF'
     - 'ON'
     - Tivo
     - PS3
    initial: 'OFF'

octoprint:
  host: 10.0.0.10 
  api_key: !secret octoprint_key

binary_sensor:
  - platform: octoprint
    monitored_conditions:
      - Printing
      - Printing Error
  - platform: iss
    # uncomment to show on map with devices
    #show_on_map: True

mqtt:
  broker: 192.168.1.175 
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_passwd

notify:
  - name: "Simplepush Keith"
    platform: simplepush
    device_key: !secret simplepush_key
  - name: "Speak to Keith"
    platform: lannouncer
    host: 10.0.0.6
  - name: "Speak to Keith VPN"
    platform: lannouncer
    host: 10.8.0.6

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: True
    waypoint_whitelist:
      - Keith 
  - platform: ping
    hosts: 
      chucks_phone: 192.168.1.3
      whitestar: 192.168.1.233  # Chuck's laptop
      lindas_phone: 192.168.1.237
      jenns_phone: 10.0.0.7
  - platform: nmap_tracker
    hosts:
      - 10.0.0.1/24
    exclude:
      - 10.0.0.152

# Sensors
sensor: !include sensors.yaml

group: !include groups.yaml

zone: !include zones.yaml

camera: !include cameras.yaml

automation: !include automations.yaml

alert: !include alerts.yaml

timer: !include timers.yaml

snips: 
  feedback_sounds: true

intent_script: !include intentscripts.yaml
